# Generated by Django 3.1.7 on 2021-03-09 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_likestatpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likestatpost',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счет'},
        ),
        migrations.CreateModel(
            name='PostComent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Author')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Комент',
                'verbose_name_plural': 'комент',
            },
        ),
    ]
