# Generated by Django 3.1.7 on 2021-03-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210310_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('time', models.IntegerField(verbose_name='patr_of_day')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('date_in', models.DateField(auto_now_add=True, verbose_name='date_in')),
            ],
            options={
                'verbose_name': 'PreOrder',
                'verbose_name_plural': 'PreOrder',
            },
        ),
    ]
