# Generated by Django 3.1.7 on 2021-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='time',
            field=models.IntegerField(choices=[(1, 'morning'), (2, 'day'), (3, 'evaning')], verbose_name='patr_of_day'),
        ),
    ]
