# Generated by Django 3.1.7 on 2021-03-23 16:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name_of_good')),
                ('about', models.CharField(max_length=50, verbose_name='About_good')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
    ]
