# Generated by Django 3.1.7 on 2021-03-30 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='month',
            field=models.CharField(max_length=2, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Num_card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='card',
            name='year',
            field=models.CharField(max_length=2, verbose_name='Year'),
        ),
    ]
