# Generated by Django 3.1.7 on 2021-04-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210330_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='month',
        ),
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='year',
        ),
        migrations.AddField(
            model_name='card',
            name='card_month',
            field=models.CharField(default=False, max_length=2, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(default=False, max_length=16, verbose_name='Card_Name'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=False, verbose_name='Card_num'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_year',
            field=models.CharField(default=False, max_length=2, verbose_name='Year'),
        ),
    ]
