# Generated by Django 3.1.7 on 2021-04-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_auto_20210401_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='None', max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(default='None', max_length=64, verbose_name='Last name')),
                ('br_date', models.DateField(verbose_name='Birthday')),
                ('email', models.CharField(default='None', max_length=64, verbose_name='Email')),
                ('avatar', models.FileField(default='none', upload_to='users_photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
